"""Crear modelos para el foro

Revision ID: 356f5ed74994
Revises: 9fcc765d2ba2
Create Date: 2026-07-13 11:08:17.735726

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '356f5ed74994'
down_revision: Union[str, Sequence[str], None] = '9fcc765d2ba2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('publicaciones',
    sa.Column('id_publicacion', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(), nullable=True),
    sa.Column('contenido', sa.String(), nullable=True),
    sa.Column('fecha_creacion', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=True),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_publicacion')
    )
    op.create_index(op.f('ix_publicaciones_id_publicacion'), 'publicaciones', ['id_publicacion'], unique=False)
    op.create_index(op.f('ix_publicaciones_titulo'), 'publicaciones', ['titulo'], unique=False)
    op.create_table('comentarios',
    sa.Column('id_comentario', sa.Integer(), nullable=False),
    sa.Column('contenido', sa.String(), nullable=True),
    sa.Column('fecha_creacion', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=True),
    sa.Column('id_publicacion', sa.Integer(), nullable=True),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_publicacion'], ['publicaciones.id_publicacion'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_comentario')
    )
    op.create_index(op.f('ix_comentarios_id_comentario'), 'comentarios', ['id_comentario'], unique=False)
    op.drop_index(op.f('ix_cuestionario_id_cuestionario'), table_name='cuestionarios')
    op.drop_index(op.f('ix_cuestionario_nombre'), table_name='cuestionarios')
    op.create_index(op.f('ix_cuestionarios_id_cuestionario'), 'cuestionarios', ['id_cuestionario'], unique=False)
    op.create_index(op.f('ix_cuestionarios_nombre'), 'cuestionarios', ['nombre'], unique=False)
    op.drop_index(op.f('ix_medio_cultivo_id_medio'), table_name='medios_cultivo')
    op.drop_index(op.f('ix_medio_cultivo_nombre'), table_name='medios_cultivo')
    op.create_index(op.f('ix_medios_cultivo_id_medio'), 'medios_cultivo', ['id_medio'], unique=False)
    op.create_index(op.f('ix_medios_cultivo_nombre'), 'medios_cultivo', ['nombre'], unique=False)
    op.drop_index(op.f('ix_medio_microorganismo_id_medio_micro'), table_name='medios_microorganismos')
    op.create_index(op.f('ix_medios_microorganismos_id_medio_micro'), 'medios_microorganismos', ['id_medio_micro'], unique=False)
    op.drop_index(op.f('ix_microorganismo_id_microorganismo'), table_name='microorganismos')
    op.drop_index(op.f('ix_microorganismo_nombre'), table_name='microorganismos')
    op.create_index(op.f('ix_microorganismos_id_microorganismo'), 'microorganismos', ['id_microorganismo'], unique=False)
    op.create_index(op.f('ix_microorganismos_nombre'), 'microorganismos', ['nombre'], unique=False)
    op.drop_index(op.f('ix_opcion_prueba_id_opcion_prueba'), table_name='opciones_prueba')
    op.create_index(op.f('ix_opciones_prueba_id_opcion_prueba'), 'opciones_prueba', ['id_opcion_prueba'], unique=False)
    op.drop_index(op.f('ix_resultado_cuestionario_id_resultado_cues'), table_name='resultados_cuestionario')
    op.create_index(op.f('ix_resultados_cuestionario_id_resultado_cues'), 'resultados_cuestionario', ['id_resultado_cues'], unique=False)
    op.drop_index(op.f('ix_resultado_prueba_micro_id_resultado'), table_name='resultados_prueba_micro')
    op.create_index(op.f('ix_resultados_prueba_micro_id_resultado'), 'resultados_prueba_micro', ['id_resultado'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_resultados_prueba_micro_id_resultado'), table_name='resultados_prueba_micro')
    op.create_index(op.f('ix_resultado_prueba_micro_id_resultado'), 'resultados_prueba_micro', ['id_resultado'], unique=False)
    op.drop_index(op.f('ix_resultados_cuestionario_id_resultado_cues'), table_name='resultados_cuestionario')
    op.create_index(op.f('ix_resultado_cuestionario_id_resultado_cues'), 'resultados_cuestionario', ['id_resultado_cues'], unique=False)
    op.drop_index(op.f('ix_opciones_prueba_id_opcion_prueba'), table_name='opciones_prueba')
    op.create_index(op.f('ix_opcion_prueba_id_opcion_prueba'), 'opciones_prueba', ['id_opcion_prueba'], unique=False)
    op.drop_index(op.f('ix_microorganismos_nombre'), table_name='microorganismos')
    op.drop_index(op.f('ix_microorganismos_id_microorganismo'), table_name='microorganismos')
    op.create_index(op.f('ix_microorganismo_nombre'), 'microorganismos', ['nombre'], unique=False)
    op.create_index(op.f('ix_microorganismo_id_microorganismo'), 'microorganismos', ['id_microorganismo'], unique=False)
    op.drop_index(op.f('ix_medios_microorganismos_id_medio_micro'), table_name='medios_microorganismos')
    op.create_index(op.f('ix_medio_microorganismo_id_medio_micro'), 'medios_microorganismos', ['id_medio_micro'], unique=False)
    op.drop_index(op.f('ix_medios_cultivo_nombre'), table_name='medios_cultivo')
    op.drop_index(op.f('ix_medios_cultivo_id_medio'), table_name='medios_cultivo')
    op.create_index(op.f('ix_medio_cultivo_nombre'), 'medios_cultivo', ['nombre'], unique=False)
    op.create_index(op.f('ix_medio_cultivo_id_medio'), 'medios_cultivo', ['id_medio'], unique=False)
    op.drop_index(op.f('ix_cuestionarios_nombre'), table_name='cuestionarios')
    op.drop_index(op.f('ix_cuestionarios_id_cuestionario'), table_name='cuestionarios')
    op.create_index(op.f('ix_cuestionario_nombre'), 'cuestionarios', ['nombre'], unique=False)
    op.create_index(op.f('ix_cuestionario_id_cuestionario'), 'cuestionarios', ['id_cuestionario'], unique=False)
    op.drop_index(op.f('ix_comentarios_id_comentario'), table_name='comentarios')
    op.drop_table('comentarios')
    op.drop_index(op.f('ix_publicaciones_titulo'), table_name='publicaciones')
    op.drop_index(op.f('ix_publicaciones_id_publicacion'), table_name='publicaciones')
    op.drop_table('publicaciones')
    # ### end Alembic commands ###
