"""Correcion de opcion_prueba

Revision ID: 4a023858cb85
Revises: 632c23f362fe
Create Date: 2026-08-13 10:34:10.958943

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a023858cb85'
down_revision: Union[str, Sequence[str], None] = '632c23f362fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resultados_prueba_micro', sa.Column('id_opcion', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'resultados_prueba_micro', 'opciones_prueba', ['id_opcion'], ['id_opcion_prueba'])
    op.drop_column('resultados_prueba_micro', 'resultado')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resultados_prueba_micro', sa.Column('resultado', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'resultados_prueba_micro', type_='foreignkey')
    op.drop_column('resultados_prueba_micro', 'id_opcion')
    # ### end Alembic commands ###
