"""Se agrego categoria a publicaciones

Revision ID: 5612e1760603
Revises: 27b34205aff2
Create Date: 2026-09-07 08:51:08.048258

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5612e1760603'
down_revision: Union[str, Sequence[str], None] = '27b34205aff2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('publicaciones', sa.Column('categoria', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('publicaciones', 'categoria')
    # ### end Alembic commands ###
