"""Tablas faltantes y relaciones

Revision ID: 62da52a02a63
Revises: 88612c1cc5cf
Create Date: 2026-06-04 13:09:47.185953

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62da52a02a63'
down_revision: Union[str, Sequence[str], None] = '88612c1cc5cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('antibiograma_microorganismo',
    sa.Column('id_anti_micro', sa.Integer(), nullable=False),
    sa.Column('resultado', sa.String(), nullable=True),
    sa.Column('id_micro', sa.Integer(), nullable=True),
    sa.Column('id_antibiograma', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_antibiograma'], ['antibiograma.id_antibiograma'], ),
    sa.ForeignKeyConstraint(['id_micro'], ['microorganismo.id_microorganismo'], ),
    sa.PrimaryKeyConstraint('id_anti_micro')
    )
    op.create_index(op.f('ix_antibiograma_microorganismo_id_anti_micro'), 'antibiograma_microorganismo', ['id_anti_micro'], unique=False)
    op.create_table('cuestionario',
    sa.Column('id_cuestionario', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=True),
    sa.Column('fecha', sa.Date(), server_default=sa.text('now()'), nullable=True),
    sa.Column('estado', sa.Boolean(), nullable=True),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_cuestionario')
    )
    op.create_index(op.f('ix_cuestionario_id_cuestionario'), 'cuestionario', ['id_cuestionario'], unique=False)
    op.create_index(op.f('ix_cuestionario_nombre'), 'cuestionario', ['nombre'], unique=False)
    op.create_table('medio_microorganismo',
    sa.Column('id_medio_micro', sa.Integer(), nullable=False),
    sa.Column('id_micro', sa.Integer(), nullable=True),
    sa.Column('id_medio', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_medio'], ['medio_cultivo.id_medio'], ),
    sa.ForeignKeyConstraint(['id_micro'], ['microorganismo.id_microorganismo'], ),
    sa.PrimaryKeyConstraint('id_medio_micro')
    )
    op.create_index(op.f('ix_medio_microorganismo_id_medio_micro'), 'medio_microorganismo', ['id_medio_micro'], unique=False)
    op.create_table('opcion_prueba',
    sa.Column('id_opcion_prueba', sa.Integer(), nullable=False),
    sa.Column('nombre_resultado', sa.String(), nullable=True),
    sa.Column('descripcion_resultado', sa.String(), nullable=True),
    sa.Column('imagen_resultado', sa.String(), nullable=True),
    sa.Column('id_prueba', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_prueba'], ['pruebas_bioquimicas.id_prueba'], ),
    sa.PrimaryKeyConstraint('id_opcion_prueba')
    )
    op.create_index(op.f('ix_opcion_prueba_id_opcion_prueba'), 'opcion_prueba', ['id_opcion_prueba'], unique=False)
    op.create_table('resultado_prueba_micro',
    sa.Column('id_resultado', sa.Integer(), nullable=False),
    sa.Column('resultado', sa.String(), nullable=True),
    sa.Column('id_micro', sa.Integer(), nullable=True),
    sa.Column('id_prueba', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_micro'], ['microorganismo.id_microorganismo'], ),
    sa.ForeignKeyConstraint(['id_prueba'], ['pruebas_bioquimicas.id_prueba'], ),
    sa.PrimaryKeyConstraint('id_resultado')
    )
    op.create_index(op.f('ix_resultado_prueba_micro_id_resultado'), 'resultado_prueba_micro', ['id_resultado'], unique=False)
    op.create_table('resultado_cuestionario',
    sa.Column('id_resultado_cues', sa.Integer(), nullable=False),
    sa.Column('resultado', sa.String(), nullable=True),
    sa.Column('id_cuesti', sa.Integer(), nullable=True),
    sa.Column('id_prueba', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_cuesti'], ['cuestionario.id_cuestionario'], ),
    sa.ForeignKeyConstraint(['id_prueba'], ['pruebas_bioquimicas.id_prueba'], ),
    sa.PrimaryKeyConstraint('id_resultado_cues')
    )
    op.create_index(op.f('ix_resultado_cuestionario_id_resultado_cues'), 'resultado_cuestionario', ['id_resultado_cues'], unique=False)
    op.alter_column('antibiograma', 'id_antibiograma',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('medio_cultivo', 'id_medio',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('microorganismo', 'id_microorganismo',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('pruebas_bioquimicas', 'id_prueba',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('usuarios', 'id_usuario',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('usuarios', 'id_usuario',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('pruebas_bioquimicas', 'id_prueba',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('microorganismo', 'id_microorganismo',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('medio_cultivo', 'id_medio',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('antibiograma', 'id_antibiograma',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_index(op.f('ix_resultado_cuestionario_id_resultado_cues'), table_name='resultado_cuestionario')
    op.drop_table('resultado_cuestionario')
    op.drop_index(op.f('ix_resultado_prueba_micro_id_resultado'), table_name='resultado_prueba_micro')
    op.drop_table('resultado_prueba_micro')
    op.drop_index(op.f('ix_opcion_prueba_id_opcion_prueba'), table_name='opcion_prueba')
    op.drop_table('opcion_prueba')
    op.drop_index(op.f('ix_medio_microorganismo_id_medio_micro'), table_name='medio_microorganismo')
    op.drop_table('medio_microorganismo')
    op.drop_index(op.f('ix_cuestionario_nombre'), table_name='cuestionario')
    op.drop_index(op.f('ix_cuestionario_id_cuestionario'), table_name='cuestionario')
    op.drop_table('cuestionario')
    op.drop_index(op.f('ix_antibiograma_microorganismo_id_anti_micro'), table_name='antibiograma_microorganismo')
    op.drop_table('antibiograma_microorganismo')
    # ### end Alembic commands ###
