"""Eliminar estado de cuestionario

Revision ID: 632c23f362fe
Revises: 356f5ed74994
Create Date: 2026-07-14 10:44:55.709278

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '632c23f362fe'
down_revision: Union[str, Sequence[str], None] = '356f5ed74994'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cuestionarios', 'estado')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cuestionarios', sa.Column('estado', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
