"""Tablas sin relaciones

Revision ID: 88612c1cc5cf
Revises: 
Create Date: 2026-06-04 11:35:55.674714

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88612c1cc5cf'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('antibiograma',
    sa.Column('id_antibiograma', sa.BigInteger(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=True),
    sa.Column('descripcion', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id_antibiograma')
    )
    op.create_index(op.f('ix_antibiograma_id_antibiograma'), 'antibiograma', ['id_antibiograma'], unique=False)
    op.create_index(op.f('ix_antibiograma_nombre'), 'antibiograma', ['nombre'], unique=False)
    op.create_table('medio_cultivo',
    sa.Column('id_medio', sa.BigInteger(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=True),
    sa.Column('procedimiento', sa.String(), nullable=True),
    sa.Column('imagen', sa.String(), nullable=True),
    sa.Column('tipo_muestra', sa.String(), nullable=True),
    sa.Column('descripcion', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id_medio')
    )
    op.create_index(op.f('ix_medio_cultivo_id_medio'), 'medio_cultivo', ['id_medio'], unique=False)
    op.create_index(op.f('ix_medio_cultivo_nombre'), 'medio_cultivo', ['nombre'], unique=False)
    op.create_table('microorganismo',
    sa.Column('id_microorganismo', sa.BigInteger(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=True),
    sa.Column('gram', sa.String(), nullable=True),
    sa.Column('forma', sa.String(), nullable=True),
    sa.Column('descripcion', sa.String(), nullable=True),
    sa.Column('imagen', sa.String(), nullable=True),
    sa.Column('tipo', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id_microorganismo')
    )
    op.create_index(op.f('ix_microorganismo_id_microorganismo'), 'microorganismo', ['id_microorganismo'], unique=False)
    op.create_index(op.f('ix_microorganismo_nombre'), 'microorganismo', ['nombre'], unique=False)
    op.create_table('pruebas_bioquimicas',
    sa.Column('id_prueba', sa.BigInteger(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=True),
    sa.Column('tipo_resultado', sa.String(), nullable=True),
    sa.Column('fundamento', sa.String(), nullable=True),
    sa.Column('tiempo_reaccion', sa.String(), nullable=True),
    sa.Column('descripcion', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id_prueba')
    )
    op.create_index(op.f('ix_pruebas_bioquimicas_id_prueba'), 'pruebas_bioquimicas', ['id_prueba'], unique=False)
    op.create_index(op.f('ix_pruebas_bioquimicas_nombre'), 'pruebas_bioquimicas', ['nombre'], unique=False)
    op.create_table('usuarios',
    sa.Column('id_usuario', sa.BigInteger(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=True),
    sa.Column('apellido', sa.String(), nullable=True),
    sa.Column('correo', sa.String(), nullable=True),
    sa.Column('contraseña', sa.String(), nullable=True),
    sa.Column('fecha_registro', sa.Date(), nullable=True),
    sa.Column('estado', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id_usuario')
    )
    op.create_index(op.f('ix_usuarios_correo'), 'usuarios', ['correo'], unique=True)
    op.create_index(op.f('ix_usuarios_id_usuario'), 'usuarios', ['id_usuario'], unique=False)
    op.create_index(op.f('ix_usuarios_nombre'), 'usuarios', ['nombre'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usuarios_nombre'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_id_usuario'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_correo'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_index(op.f('ix_pruebas_bioquimicas_nombre'), table_name='pruebas_bioquimicas')
    op.drop_index(op.f('ix_pruebas_bioquimicas_id_prueba'), table_name='pruebas_bioquimicas')
    op.drop_table('pruebas_bioquimicas')
    op.drop_index(op.f('ix_microorganismo_nombre'), table_name='microorganismo')
    op.drop_index(op.f('ix_microorganismo_id_microorganismo'), table_name='microorganismo')
    op.drop_table('microorganismo')
    op.drop_index(op.f('ix_medio_cultivo_nombre'), table_name='medio_cultivo')
    op.drop_index(op.f('ix_medio_cultivo_id_medio'), table_name='medio_cultivo')
    op.drop_table('medio_cultivo')
    op.drop_index(op.f('ix_antibiograma_nombre'), table_name='antibiograma')
    op.drop_index(op.f('ix_antibiograma_id_antibiograma'), table_name='antibiograma')
    op.drop_table('antibiograma')
    # ### end Alembic commands ###
